config/routes.rb
Rails.application.routes.draw do

  resources :results
  resources :second_synthetic_accounts
  resources :analytic_accounts
  resources :synthetic_accounts
  resources :operations, except: [:edit, :update] 
  resources :accounts
  resources :account_types
  resources :chart_of_accounts
  resources :companies
  resources :form_wizard
  

devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  authenticated :user do
      root 'welcome#dashboard', as: :authenticated_root
  end
  get 'checar_data', to: 'results#check_valid_date', as: :check_valid_date
  get 'selecionar_periodo', to: 'results#selecionar_periodo', as: :result_search
  get 'control_users/index'
  get 'dashboard', to: 'welcome#dashboard', as: :dashboard
  get 'livro_diario', to: 'operations#index', as: :daily_ledger
  get 'livro_razao', to: 'ledger#index', as: :ledger
  get 'cadastrar/contas', to: 'form_wizard#index', as: :wizard_index
  resources :enterprises
  post 'authorize_operation/:id', to: 'operations#authorize_operation', as: :authorize_operation
  get 'authorize_all', to: 'operations#authorize_all', as: :authorize_all
  
  get 'analytic_ledger/:id', to: 'analytic_accounts#analytic_ledger', as: :analytic_ledger
  get 'home', to: 'home#visitors', as: :visitors
  get 'nova_senha', to: 'home#password', as: :forget_password
  root 'home#visitors'

end

app/models/second_synthetic_account.rb
class SecondSyntheticAccount < ActiveRecord::Base
  belongs_to :synthetic_account

  has_many :analytic_accounts, dependent: :destroy

  def second_synthetic_account_name
    "#{synthetic_account.account.account_type.code}.#{synthetic_account.account.code}.#{synthetic_account.code}.#{code} - #{name}"
  end
end

app/controllers/second_synthetic_accounts_controller.rb
class SecondSyntheticAccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_second_synthetic_account, only: [:show, :edit, :update, :destroy]

  # GET /second_synthetic_accounts
  # GET /second_synthetic_accounts.json
  def index
    @second_synthetic_accounts = SecondSyntheticAccount.all
  end

  # GET /second_synthetic_accounts/1
  # GET /second_synthetic_accounts/1.json
  def show
  end

  # GET /second_synthetic_accounts/new
  def new
    @second_synthetic_account = SecondSyntheticAccount.new
    
  end

  # GET /second_synthetic_accounts/1/edit
  def edit
  end

  # POST /second_synthetic_accounts
  # POST /second_synthetic_accounts.json
  def create
    @second_synthetic_account = SecondSyntheticAccount.new(second_synthetic_account_params)

    respond_to do |format|
      if @second_synthetic_account.save
        format.html { redirect_to new_analytic_account_path, notice: 'Conta criada com sucesso.' }
        
      else
        format.html { render :new }
        format.json { render json: @second_synthetic_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /second_synthetic_accounts/1
  # PATCH/PUT /second_synthetic_accounts/1.json
  def update
    respond_to do |format|
      if @second_synthetic_account.update(second_synthetic_account_params)
        format.html { redirect_to @second_synthetic_account, notice: 'Second synthetic account was successfully updated.' }
        format.json { render :show, status: :ok, location: @second_synthetic_account }
      else
        format.html { render :edit }
        format.json { render json: @second_synthetic_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /second_synthetic_accounts/1
  # DELETE /second_synthetic_accounts/1.json
  def destroy
    @second_synthetic_account.destroy
    respond_to do |format|
      format.html { redirect_to second_synthetic_accounts_url, notice: 'Second synthetic account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_second_synthetic_account
      @second_synthetic_account = SecondSyntheticAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def second_synthetic_account_params
      params.require(:second_synthetic_account).permit(:code, :name, :description, :balance, :synthetic_account_id)
    end
end

app/helpers/second_synthetic_accounts_helper.rb
module SecondSyntheticAccountsHelper
end

app/views/second_synthetic_accounts/_form.html.erb
<%= form_for(@second_synthetic_account) do |f| %>
  <% if @second_synthetic_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@second_synthetic_account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @second_synthetic_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      
      <div class="row">
      <div class="col-md-4">

      <div class="input-group">
        <span class="input-group-addon " id="basic-addon1"><i class="fa fa-tag" aria-hidden="true"></i></span>
       <%= f.text_field :code, class:"form-control", describedby: "basic-addon1", placeholder: "Insira o número da conta", id: "code"%>
      </div>
      </div>
      </div>
      <br>

      <div class="row">
      <div class="col-md-4">

      <div class="input-group">
        <span class="input-group-addon " id="basic-addon2"><i class="fa fa-briefcase" aria-hidden="true"></i></span>
       <%= f.text_field :name, class:"form-control", describedby: "basic-addon2", placeholder: "Insira o nome da conta"%>
      </div>
      </div>
      </div>
      </br>
      <div class="row">
      <div class="col-md-4">

      <div class="input-group">
        
      <label for="account_type_id">
      Click na caixa de seleção abaixo para selecionar a Conta ao qual pertence<br>
      <%= f.collection_select :synthetic_account_id, SyntheticAccount.all, :id, :synthetic_account_name, {default: SyntheticAccount.take}, {class:"form-control parent_account", include_blank: false} %>
   
      </label>
      </div>
      </div>
      </div>
      <br>

  <div class="actions">
  <div class="col-md-4">
    <%= f.submit "Criar conta", class: "btn btn-primary" %>
    <%= link_to 'Voltar', wizard_index_path, class: "btn btn-danger btn-sm pull-right" %>
  </div>
  </div>
<% end %>

app/views/second_synthetic_accounts/edit.html.erb
<h1>Editando Conta de Quarto Nível</h1>

<%= render 'form' %>

<%= link_to 'Show', @second_synthetic_account %> |
<%= link_to 'Back', second_synthetic_accounts_path %>

app/views/second_synthetic_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Second Synthetic Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Description</th>
      <th>Balance</th>
      <th>Synthetic account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @second_synthetic_accounts.each do |second_synthetic_account| %>
      <tr>
        <td><%= second_synthetic_account.code %></td>
        <td><%= second_synthetic_account.name %></td>
        <td><%= second_synthetic_account.description %></td>
        <td><%= second_synthetic_account.balance %></td>
        <td><%= second_synthetic_account.synthetic_account %></td>
        <td><%= link_to 'Show', second_synthetic_account %></td>
        <td><%= link_to 'Edit', edit_second_synthetic_account_path(second_synthetic_account) %></td>
        <td><%= link_to 'Destroy', second_synthetic_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Second synthetic account', new_second_synthetic_account_path %>

app/views/second_synthetic_accounts/new.html.erb
<h1>Nova Conta de Quarto Nível</h1>

<%= render 'form' %>

app/views/second_synthetic_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @second_synthetic_account.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @second_synthetic_account.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @second_synthetic_account.description %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @second_synthetic_account.balance %>
</p>

<p>
  <strong>Synthetic account:</strong>
  <%= @second_synthetic_account.synthetic_account %>
</p>

<%= link_to 'Edit', edit_second_synthetic_account_path(@second_synthetic_account) %> |
<%= link_to 'Back', second_synthetic_accounts_path %>