config/routes.rb
Rails.application.routes.draw do

  resources :results
  resources :second_synthetic_accounts
  resources :analytic_accounts
  resources :synthetic_accounts
  resources :operations, except: [:edit, :update] 
  resources :accounts
  resources :account_types
  resources :chart_of_accounts
  resources :companies
  resources :form_wizard
  

devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  authenticated :user do
      root 'welcome#dashboard', as: :authenticated_root
  end
  get 'checar_data', to: 'results#check_valid_date', as: :check_valid_date
  get 'selecionar_periodo', to: 'results#selecionar_periodo', as: :result_search
  get 'control_users/index'
  get 'dashboard', to: 'welcome#dashboard', as: :dashboard
  get 'livro_diario', to: 'operations#index', as: :daily_ledger
  get 'livro_razao', to: 'ledger#index', as: :ledger
  get 'cadastrar/contas', to: 'form_wizard#index', as: :wizard_index
  resources :enterprises
  post 'authorize_operation/:id', to: 'operations#authorize_operation', as: :authorize_operation
  get 'authorize_all', to: 'operations#authorize_all', as: :authorize_all
  
  get 'analytic_ledger/:id', to: 'analytic_accounts#analytic_ledger', as: :analytic_ledger
  get 'home', to: 'home#visitors', as: :visitors
  get 'nova_senha', to: 'home#password', as: :forget_password
  root 'home#visitors'

end

app/models/analytic_account.rb
class AnalyticAccount < ActiveRecord::Base
  belongs_to :second_synthetic_account

  belongs_to :listenable, polymorphic: true

  has_many :debits, class_name: "Operation",
                          foreign_key: "retrieve_account_id", dependent: :destroy
  has_many :credits, class_name: "Operation",
                          foreign_key: "release_account_id", dependent: :destroy
  has_many :old_balances

  has_one :result

  def self.name_search(search)
      @name_a_search = search
    if search
      where("name ILIKE ? ", "%#{@name_a_search}%")
    else
      where(nil)
    end
  end

  def self.debits

    debit.where(release_date: date1..date2 )

  end

  def self.credits

    credit.where(release_date: date1..date2 )

  end

  def self.order_by_code
      includes(second_synthetic_account: {synthetic_account: {account: :account_type}}).
      order('account_types.code').order('accounts.code').order('synthetic_accounts.code').
      order('second_synthetic_accounts.code').order(:code)

  end

  def self.result_accounts date_init, date_final, nature

      if date_init.class.equal?Date and date_final.class.equal?Date
        @init_date = date_init
        @final_date = date_final
      else
        @init_date = Date.strptime(date_init, "%d/%m/%Y")
        @final_date = Date.strptime(date_final, "%d/%m/%Y")
      end

      if nature.eql?"D"

        includes(:debits, second_synthetic_account: {synthetic_account: {account: :account_type}}).
        where(account_types: {code: [4,5]}).
        where(operations: {release_date: @init_date..@final_date})

      elsif nature.eql?"C"

        includes(:credits, second_synthetic_account: {synthetic_account: {account: :account_type}}).
        where(account_types: {code: [3]}).where(operations: {release_date: @init_date..@final_date}).
        where.not(second_synthetic_accounts: {code: [2]})
      elsif nature.eql?"BOTH"

        credits = includes(:debits, second_synthetic_account: {synthetic_account: {account: :account_type}}).
        where(account_types: {code: [4,5]}).
        where(operations: {release_date: @init_date..@final_date})
        debits = includes(:credits, second_synthetic_account: {synthetic_account: {account: :account_type}}).
        where(account_types: {code: [3]}).where(operations: {release_date: @init_date..@final_date}).
        where.not(second_synthetic_accounts: {code: [2]})
        credits + debits
      else
        nil
      end
  end

  def analytic_account_name
    "#{second_synthetic_account.synthetic_account.account.account_type.code}.
    #{second_synthetic_account.synthetic_account.account.code}.
    #{second_synthetic_account.synthetic_account.code}.
    #{second_synthetic_account.code}.
    #{code} - #{name}"

  end

  
  def old_balance op

  		OldBalance.find_by(operation: op, analytic_account: self)
  end

end

app/controllers/analytic_accounts_controller.rb
class AnalyticAccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_analytic_account, only: [:show, :edit, :update, :destroy, :analytic_ledger]

  # GET /analytic_accounts
  # GET /analytic_accounts.json
  def index
    @analytic_accounts = AnalyticAccount.all


  end

  def analytic_ledger
    @q = Operation.ransack(params[:q])
    @operations = @q.result.includes(:retrieve_account).where(retrieve_account:
                                                             @analytic_account)
    @operations << @q.result.includes(:release_account).where(release_account: @analytic_account)

    @balance = @analytic_account.old_balances.where('operation_id in (?)', @operations.to_a).sum(:value)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "relatório"
      end
    end
  end




  # GET /analytic_accounts/1
  # GET /analytic_accounts/1.json
  def show
    @operations = Operation.includes(:retrieve_account).where(retrieve_account:
                                                             @analytic_account)
    @operations += Operation.includes(:release_account).where(release_account: @analytic_account)


  end

  # GET /analytic_accounts/new
  def new
    @analytic_account = AnalyticAccount.new
  end

  # GET /analytic_accounts/1/edit
  def edit
  end

  # POST /analytic_accounts
  # POST /analytic_accounts.json
  def create
    @analytic_account = AnalyticAccount.new(analytic_account_params)

    respond_to do |format|
      if @analytic_account.save
        format.html { redirect_to wizard_index_path, notice: 'Analytic account was successfully created.' }

      else
        format.html { render :new }
        format.json { render json: @analytic_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analytic_accounts/1
  # PATCH/PUT /analytic_accounts/1.json
  def update
    respond_to do |format|
      if @analytic_account.update(analytic_account_params)
        format.html { redirect_to @analytic_account, notice: 'Analytic account was successfully updated.' }
        format.json { render :show, status: :ok, location: @analytic_account }
      else
        format.html { render :edit }
        format.json { render json: @analytic_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analytic_accounts/1
  # DELETE /analytic_accounts/1.json
  def destroy
    @analytic_account.destroy
    respond_to do |format|
      format.html { redirect_to analytic_accounts_url, notice: 'Analytic account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analytic_account
      @analytic_account = AnalyticAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analytic_account_params
      params.require(:analytic_account).permit(:code, :name, :description, :balance, :second_synthetic_account_id)
    end


end

app/helpers/analytic_accounts_helper.rb
module AnalyticAccountsHelper
	def parent_accounts
		@accounts = SecondSyntheticAccount.all

	end

end

app/views/analytic_accounts/_form.html.erb
<div class="container-fluid">
<%= form_for(@analytic_account) do |f| %>
  <% if @analytic_account.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@analytic_account.errors.count, "error") %> prohibited this analytic_account from being saved:</h2>

    <ul>
      <% @analytic_account.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="row">
    <div class="col-md-4">

      <div class="input-group">
        <span class="input-group-addon " id="basic-addon1"><i class="fa fa-tag" aria-hidden="true"></i></span>
        <%= f.text_field :code, class:"form-control", describedby: "basic-addon1", placeholder: "Insira o número da conta", id: "code"%>

      </div>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-md-4">

      <div class="input-group">
        <span class="input-group-addon " id="basic-addon2"><i class="fa fa-briefcase" aria-hidden="true"></i></span>
        <%= f.text_field :name, class:"form-control", describedby: "basic-addon2", placeholder: "Insira o nome da conta"%>
      </div>
    </div>
  </div>
</br>
<div class="row">
  <div class="col-md-4">

    <div class="input-group">

      <label for="account_type_id">
        Click na caixa de seleção abaixo para selecionar a Conta Pai<br>
        <%= f.collection_select :second_synthetic_account_id, parent_accounts, :id, :second_synthetic_account_name, {}, {class:"form-control parent_account"} %>

      </label>
    </div>
  </div>
</div>
<br>

  <div class="actions">
    <div class="col-md-4">
      <%= f.submit "Criar conta", class: "btn btn-primary" %>
      <%= link_to 'Voltar', wizard_index_path, class: "btn btn-danger btn-sm pull-right" %>
    </div>
  </div>
  <% end %>

</div>

app/views/analytic_accounts/_search.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="input-group" id="adv-search"><p>Pesquisar por período</p>
      <div class="input-group-btn">
        <div class="btn-group" role="group">
          <%= search_form_for @q, url: analytic_ledger_path, class: "form-horizontal" do |f|  %>
          <div class="form-group pull-right">
            <%= f.label "Período inicial" %>
            <%= f.search_field :release_date_gteq, placeholder: "Periodo inicial", input_html: {class: "date", value: "#{f.object.release_date_gteq.strftime('%d-%m-%Y') unless params[:release_date_gteq].nil?}"},  class: "input-sm date", default: Time.now%>
            <%= f.label "Período final" %>
            <%= f.search_field :release_date_lteq, placeholder: "Periodo final", input_html: {class: "date", value: "#{f.object.release_date_lteq.strftime('%d-%m-%Y') unless params[:release_date_lteq].nil?}"},  class: "input-sm date " %> 
            <%= f.submit  class: "btn btn-primary" %>
          </div>
          
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/analytic_accounts/analytic_ledger.html.erb
<div class="container-fluid">
  <h1 class="page-header"><strong>Livro Razão <%= @analytic_account.name %></strong></h1>
     <div class="panel panel-default">
      <div class="panel-heading text-center">
      <%= render 'search' %>
      <strong><%= Company.last.name %></strong></div>
      <table class="table ">
        <thead>
          <tr>
            <th>Data</th>
            <th>Número da Operação</th>
            <th>Contrapartida</th>
            <th>Histórico</th>
            <th>Débito</th>
            <th>Crédito</th>
            <th>Saldo Anterior</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @operations.order(:release_date).each  do |op| %>
        <tbody>
        <% if op.authorized? %>
          <tr>
            <td><%= op.release_date.strftime("%d/%m/%Y") %></td>
            <td><%= op.id %></td>
            <% if op.release_account.eql?(@analytic_account)%>

            <td><%= op.retrieve_account.name %></td>
            <% else %>

            <td><%= op.release_account.name %></td>
            <% end %>
            <td><%= op.description %></td>
            <td><%= number_to_currency(op.value, unit: "R$", separator: ",", delimiter: ".") if op.retrieve_account.eql?(@analytic_account) %></td>
            <td><%= number_to_currency(op.value, unit: "R$", separator: ",", delimiter: ".") if op.release_account.eql?(@analytic_account) %></td>
            <td><%= number_to_currency(OldBalance.balance(op, @analytic_account), unit: "R$", separator: ",", delimiter: ".")%></td>
          </tr>

        <% end %>

        </tbody>
        <% end %>
      </table>
      <div class="panel-footer"><strong>Total: <%= number_to_currency(@balance, unit: "R$", separator: ",", delimiter: ".") %></strong></div>
    </div>

<%= link_to 'Gerar relatório', analytic_ledger_path(@analytic_account, format: 'pdf'), class: "btn btn-primary" %>
</div>

app/views/analytic_accounts/analytic_ledger.pdf.erb
<!doctype html>
<html>
 <head>
   <meta charset='utf-8' />
   <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
   <%= wicked_pdf_javascript_include_tag "number_pages" %>
   <%= stylesheet_link_tag "pdf.scss" %>
 </head>

 <body onload='number_pages'>
 
<div class="container-fluid">
   <h1 class="page-header text-center"><strong><%= Company.last.name %></strong>
   <p class="page-header text-center" > CNPJ: <%= Company.last.cnpj%></p>
   <p class="page-header text-center" ><%= Company.last.address%></p>
   <p class="page-header text-center" >CEP:<%= Company.last.cep%></p>
</h1>
 <div class="row">
   <div class="panel panel-default">
     <table class="table table-bordered2">
     <thead>

       <tr>
     <th><div class="panel-heading text-center"><strong>Livro Razão</strong></div></th>
   </tr>

     <table class="table1">        <!-- MOSTRAR TODAS AS CONTAS PAI  -->
       <p class = "page-header text-right font-size"><strong> Conta contabil:
         <%= @analytic_account.second_synthetic_account.synthetic_account.account.account_type.code %>.
         <%= @analytic_account.second_synthetic_account.synthetic_account.account.code %>
         .<%= @analytic_account.second_synthetic_account.synthetic_account.code %>
         .<%= @analytic_account.second_synthetic_account.code %>
         .<%= @analytic_account.code %></strong> <span style ="padding-left:100px"><%= @analytic_account.name %></span></p>
     <thead>
         <tr class="linha">
           <th class="borda">Data</th>
           <th class="borda">Contrapartida</th>
           <th class="borda">Histórico</th>
           <th class="borda">Número da Operação</th>
           <th class="borda">Débito</th>
           <th class="borda">Crédito</th>
           <th class="borda">Saldo</th>
         </tr>

       </thead>
       <br>
         <br>
       <% @operations.sort_by{|task| task.id}.each do |op| %>
       <tbody >
           <tr>
           <td class="borda1"><%= op.release_date.strftime("%d/%m/%Y") %></td>
         <!--   -->
           <% if op.release_account.eql?(@analytic_account)%>
           <!-- codigo da contra partida-->
           <td class="borda1"><%= op.retrieve_account.second_synthetic_account.synthetic_account.account.account_type.code %>.
           <%= op.retrieve_account.second_synthetic_account.synthetic_account.account.code %>
           .<%= op.retrieve_account.second_synthetic_account.synthetic_account.code %>
           .<%= op.retrieve_account.second_synthetic_account.code %>
           .<%= op.retrieve_account.code %></td>
           <% else %>
           <!-- codigo da contra partida-->
           <td class="borda1"><%= op.release_account.second_synthetic_account.synthetic_account.account.account_type.code %>.
            <%= op.release_account.second_synthetic_account.synthetic_account.account.code %>
           .<%= op.release_account.second_synthetic_account.synthetic_account.code %>
           .<%= op.release_account.second_synthetic_account.code %>
           .<%= op.release_account.code %></td>
           <% end %>
           <td class="borda1"><%= op.description %></td>
           <td class="borda1"><%= op.id %></td>
           <td class="borda1"><%= number_to_currency(op.value, unit: "R$", separator: ",", delimiter: ".") if op.retrieve_account.eql?(@analytic_account) %></td>
           <td class="borda1"><%= number_to_currency(op.value, unit: "R$", separator: ",", delimiter: ".") if op.release_account.eql?(@analytic_account) %></td>
           <td class="borda1"><%=number_to_currency(OldBalance.find_by(operation: op,
            analytic_account: @analytic_account).value, unit: "R$", separator: ",", delimiter: ".") if OldBalance.find_by(operation: op,
            analytic_account: @analytic_account) %></td>

         </tr>
         </tbody>
       <% end %>
         </table>
         <strong class="total">Total:<%= number_to_currency(balance = @analytic_account.balance, unit: "R$", separator: ",", delimiter:".")%></strong>
   </div>
 </div>
</div>
</div>
</body>
</html>

app/views/analytic_accounts/edit.html.erb
<h1>Editando Conta de Quinto Nível</h1>

<%= render 'form' %>

<%= link_to 'Show', @analytic_account %> |
<%= link_to 'Back', analytic_accounts_path %>

app/views/analytic_accounts/index.html.erb
<div class="container">
  <div  class="row">
    <p id="notice"><%= notice %></p>

    <h1>Listing Analytics accounts</h1>

    <table class="table">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Description</th>
      <th>Balance</th>
      <th>Second Synthetic account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @analytic_accounts.each do |analytic_account| %>
      <tr>
        <td><%= analytic_account.second_synthetic_account.synthetic_account.account.account_type.code %>.<%= analytic_account.second_synthetic_account.synthetic_account.account.code %>.<%= analytic_account.second_synthetic_account.synthetic_account.code %>.<%= analytic_account.second_synthetic_account.code %>.<%= analytic_account.code %></td>
        <td><%= analytic_account.name %></td>
        <td><%= analytic_account.description %></td>
        <td><%= analytic_account.balance %></td>
        <td><%= analytic_account.second_synthetic_account.name %></td>
        <td><%= link_to 'Show', analytic_account, class: "btn-primary btn-sm" %>
        <%= link_to 'Edit', edit_analytic_account_path(analytic_account), class: "btn-primary btn-sm" %>
        <%= link_to 'Destroy', analytic_account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-primary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Analytic account', new_analytic_account_path, class: "btn btn-primary " %>

app/views/analytic_accounts/new.html.erb
<h1>Nova Conta de Quinto Nível</h1>

<%= render 'form' %>

app/views/analytic_accounts/show.html.erb
<div class="container-fluid">
  <h1 class="page-header"><strong>Livro Razão <%= @analytic_account.name %></strong></h1>
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading text-center"><strong><%= Company.last.name %></strong></div>
      <table class="table ">
        <thead>
          <tr>
            <th>Data</th>
            <th>Número da Operação</th>
            
            <th>Contrapartida</th>
            <th>Histórico</th>
            <th>Débito</th>
            <th>Crédito</th>
            <th>Saldo</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @operations.sort_by{|task| task.id}.each do |op| %>
        <tbody>

          <tr>
            <td><%= op.release_date %></td>
            <td><%= op.id %></td>
            <% if op.release_account.eql?(@analytic_account)%>
            
            <td><%= op.retrieve_account.name %></td>
            <% else %>
            
            <td><%= op.release_account.name %></td>
            <% end %>
            <td><%= op.description %></td>
            <td><%= op.value if op.retrieve_account.eql?(@analytic_account) %></td>
            <td><%= op.value if op.release_account.eql?(@analytic_account) %></td>
            <td><%= OldBalance.find_by(operation: op,
             analytic_account: @analytic_account).value %></td>

    
          </tr>
                  
        </tbody>
        <% end %>
        <tr><tr><tr><tr><tr><tr><td><td><td><td><td><td><strong>Total: </strong><td>
        <strong><%= @analytic_account.balance%></strong></td></tr>
          </table>  
      
    </div>

  </div>

</div>
<%= link_to 'Create PDF document', analytic_account_path(@analytic_account, :format => :pdf) %>