config/routes.rb
Rails.application.routes.draw do

  resources :results
  resources :second_synthetic_accounts
  resources :analytic_accounts
  resources :synthetic_accounts
  resources :operations, except: [:edit, :update] 
  resources :accounts
  resources :account_types
  resources :chart_of_accounts
  resources :companies
  resources :form_wizard
  

devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  authenticated :user do
      root 'welcome#dashboard', as: :authenticated_root
  end
  get 'checar_data', to: 'results#check_valid_date', as: :check_valid_date
  get 'selecionar_periodo', to: 'results#selecionar_periodo', as: :result_search
  get 'control_users/index'
  get 'dashboard', to: 'welcome#dashboard', as: :dashboard
  get 'livro_diario', to: 'operations#index', as: :daily_ledger
  get 'livro_razao', to: 'ledger#index', as: :ledger
  get 'cadastrar/contas', to: 'form_wizard#index', as: :wizard_index
  resources :enterprises
  post 'authorize_operation/:id', to: 'operations#authorize_operation', as: :authorize_operation
  get 'authorize_all', to: 'operations#authorize_all', as: :authorize_all
  
  get 'analytic_ledger/:id', to: 'analytic_accounts#analytic_ledger', as: :analytic_ledger
  get 'home', to: 'home#visitors', as: :visitors
  get 'nova_senha', to: 'home#password', as: :forget_password
  root 'home#visitors'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
layout 'devise'
	def visitors
		
	end
	def password
		
	end
end

app/helpers/home_helper.rb
module HomeHelper
  
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/_login.html.erb
<p class="lead">Faça o login para continuar a utilizar o Luzeiro Finanças</p>
<%=  form_for(:user, :url => session_path(:user)) do |f| %>


<fieldset>
  <%= f.text_field :login, autofocus: true, class: "form-control input-lg", placeholder: "Nome de Usuário ou Email" %>
  
  <%= f.password_field :password, autocomplete: "off", class: "form-control input-lg", placeholder: "Senha" %>

  <div class="checkbox">
    <label>
      <% if devise_mapping.rememberable? -%>
      <div class="field">
        <%= f.check_box :remember_me %>
        <t>Lembre-me</t>
      </div>
      <% end -%>
    </label>
  </div>
  <%= f.submit "Entrar", class: "btn btn-lg btn-success btn-block", method: :post%>
  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", forget_password_path %><br />
  <% end -%>

</fieldset>
<% end %>

app/views/home/password.html.erb
<h2>Esqueceu sua senha?</h2>

<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
  <%= devise_error_messages! %>
<fieldset>
  

    <%= f.email_field :email, autofocus: true, class: "form-control input-lg", placeholder: "E-mail"  %>
  

  <div class="actions">
    <%= f.submit "Envie-me instruções por email", class: "btn btn-lg btn-success btn-block" %>
  </div>
  </fieldset>
<% end %>

<%= link_to "Login", visitors_path %>

app/views/home/visitors.html.erb
<%= render 'login' %>
          