config/routes.rb
Rails.application.routes.draw do

  resources :results
  resources :second_synthetic_accounts
  resources :analytic_accounts
  resources :synthetic_accounts
  resources :operations, except: [:edit, :update] 
  resources :accounts
  resources :account_types
  resources :chart_of_accounts
  resources :companies
  resources :form_wizard
  

devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  authenticated :user do
      root 'welcome#dashboard', as: :authenticated_root
  end
  get 'checar_data', to: 'results#check_valid_date', as: :check_valid_date
  get 'selecionar_periodo', to: 'results#selecionar_periodo', as: :result_search
  get 'control_users/index'
  get 'dashboard', to: 'welcome#dashboard', as: :dashboard
  get 'livro_diario', to: 'operations#index', as: :daily_ledger
  get 'livro_razao', to: 'ledger#index', as: :ledger
  get 'cadastrar/contas', to: 'form_wizard#index', as: :wizard_index
  resources :enterprises
  post 'authorize_operation/:id', to: 'operations#authorize_operation', as: :authorize_operation
  get 'authorize_all', to: 'operations#authorize_all', as: :authorize_all
  
  get 'analytic_ledger/:id', to: 'analytic_accounts#analytic_ledger', as: :analytic_ledger
  get 'home', to: 'home#visitors', as: :visitors
  get 'nova_senha', to: 'home#password', as: :forget_password
  root 'home#visitors'

end

app/controllers/ledger_controller.rb
class LedgerController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:name]
      @analytic_accounts = AnalyticAccount.name_search(params[:name]).paginate(:page => params[:page], :per_page => 20  )
    else
      @analytic_accounts = AnalyticAccount.paginate(:page => params[:page], :per_page => 20  ).
      includes(second_synthetic_account: {synthetic_account: {account: :account_type}}).
      order('account_types.code').order('accounts.code').order('synthetic_accounts.code').
      order('second_synthetic_accounts.code').order(:code)
    end
    respond_to do |format|
        format.html
        format.pdf do
          render pdf: "file_name"   # Excluding ".pdf" extension.
        end
      end
  end
end

app/helpers/ledger_helper.rb
module LedgerHelper
end

app/views/ledger/index.html.erb
<div class="container-fluid">
  <div class="col-md-12">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <%= icon('dashboard', class: 'strong aumentaicon')%>Dashboard
          </div>


          <div class="col-xs-5 text-right">
            <%= link_to "Livro razão", "#", :class => "huge" %>
          </div>
        </div>
      </div>
          <%= form_tag ledger_path, :method => "get", class: "form-search" do %>
            <%= text_field_tag :name, params[:name], class:" search",placeholder: "Buscar" %>
            <%= button_tag(type: "submit") do %>
            <span class="fa fa-search"></span>
             <% end %>
            <% end %>

      <table class="table">
        <thead>
          <tr>
          	 <th>Código</th>
    	       <th>Nome</th>
    	       <th>Saldo</th>
    	       <th>  </th>
          </tr>
        </thead>
        <tbody>

          <% @analytic_accounts.each do |analytic_account| %>
	     <tr>
	       <td><%= analytic_account.second_synthetic_account.synthetic_account.account.account_type.code %>.<%= analytic_account.second_synthetic_account.synthetic_account.account.code %>.<%= analytic_account.second_synthetic_account.synthetic_account.code %>.<%= analytic_account.second_synthetic_account.code %>.<%= analytic_account.code %>
	       </td>
	       <td>
        	    <%= button_to analytic_account.second_synthetic_account.synthetic_account.account.account_type.name, account_type_path(analytic_account.second_synthetic_account.synthetic_account.account.account_type), class: "btn btn-primary icon-btn btn-xs",method: :get%>
        	    <%= button_to analytic_account.second_synthetic_account.synthetic_account.account.name.downcase, account_path(analytic_account.second_synthetic_account.synthetic_account.account), class: "btn btn-primary icon-btn btn-xs",method: :get%>
        	    <%= button_to analytic_account.second_synthetic_account.synthetic_account.name.downcase, synthetic_account_path(analytic_account.second_synthetic_account.synthetic_account), class: "btn btn-primary icon-btn btn-xs",method: :get%>
        	    <%= button_to analytic_account.second_synthetic_account.name.downcase, second_synthetic_account_path(analytic_account.second_synthetic_account), class: "btn btn-primary icon-btn btn-xs",method: :get%>
        	    <%= button_to analytic_account.name.downcase, analytic_account_path(analytic_account), class: "btn btn-primary icon-btn btn-xs",method: :get%>
      	       </td>
      	       <td><%= number_to_currency(analytic_account.old_balances.sum(:value), unit: "R$", separator: ",", delimiter: ".")%></td>
      	       <td><%= link_to 'Ver Livro Razão', analytic_ledger_path(analytic_account), class: "btn btn-success btn-sm" %></td>
	     </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-12"><%= @operations_all %></div>
  </div>
</div>